- name: Installing chaotic-aur repos.
  become: true
  shell: |
    pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    pacman-key --lsign-key 3056513887B78AEB
    pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
  tags:
    - install
    - aur

- name: Configure pacman for chaotic-aur
  become: true
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
  tags:
    - install
    - aur

- name: Update pacman cache
  become: true
  pacman: 
    update_cache: yes
  tags:
    - install
    - aur


- name: Install Yay
  become: true
  pacman: 
    name:
      - yay
  tags:
    - install
    - aur


- name: Disable password for yay
  become: true
  lineinfile:
    path: /etc/sudoers
    line: 'sdk ALL=(ALL) NOPASSWD: /usr/bin/yay'
  tags:
    - aur
