- name: Install core programs.
  become: true
  pacman:
    name:
      - alsa-utils 
      - base-devel
      - btrfs-progs
      - git
      - pipewire
      - pipewire-alsa
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - pavucontrol
      - rsync
      - stow
    
  tags: 
    - install
    - core

- name: Install NVIDIA Open Kernel Drivers
  become: true
  pacman:
    name:
      - nvidia-open
      - nvidia-utils
      - nvidia-settings
    state: present
    update_cache: true
  when: "'nvidia' in ansible_play_batch"
  tags:
    - nvidia

- name: Enable DRM modeset
  become: true
  copy:
    dest: /etc/modprobe.d/nvidia.conf
    content: |
      options nvidia-drm modeset=1
    owner: root
    group: root
    mode: '0644'
  tags:
    - nvidia

- name: Regenerate initramfs
  become: true
  command: mkinitcpio -P
  when: "'nvidia' in ansible_play_batch"
  tags:
    - nvidia

