- name: Common programs
  become: true
  pacman:
    name:
      - steam
      - flatpak
      - gamemode
      - vlc
      - zed
  tags:
    - install
    - common

- name: Yay common programs
  shell: |
    yay -S --noconfirm --needed google-chrome firefox |
    spotify-launcher 1password
  tags:
    - install
    - common
# - name: Flathub
#   shell: flatpak install flathub
#   tags:
#     - install
#     - common

# - name: Flatpak common programs
#   shell: flatpak install flathub net.davidotek.pupgui2flatpak
#   tags:
#     - install
#     - common
