- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/Personal"
  pre_tasks:
    - name: Update pacman
      become: true
      pacman:
        update_cache: true
      tags: install
  tasks:
    - include: tasks/core.yaml
    - include: tasks/ssh.yaml
    - include: tasks/zsh.yaml
    - include: tasks/nvim.yaml
    - include: tasks/desktop.yaml
    # - include: tasks/dotfiles.yaml
